#!/bin/bash
# dynamic-router.sh — Automatic Dynamic WAN + static LAN router for VMs with VPN support
# Usage: ./dynamic-router.sh --install-service <LAN_IFACE> <LAN_IP/CIDR> [--vpn] [--subnets <file>]
#        ./dynamic-router.sh --run <LAN_IFACE> <LAN_IP/CIDR> [--vpn] [--subnets <file>]
#        ./dynamic-router.sh --reset

set -e

# Hardcoded fallback DNS servers
FALLBACK_DNS1="1.1.1.1"
FALLBACK_DNS2="8.8.8.8"

# Default VPN subnets file location
VPN_SUBNETS_FILE="/etc/router/vpn-subnets.txt"

# VPN routing disabled by default
ENABLE_VPN_ROUTING=false

# Backup location for original DNS config
DNS_BACKUP="/etc/router/resolv.conf.backup"

# === Pre-flight check: Install requirements ===
check_and_install_requirements() {
    echo "[INFO] Checking system requirements..."
    
    REQUIRED_PKGS=(dnsmasq iptables iptables-persistent curl net-tools iproute2 dnsutils)
    MISSING_PKGS=()
    
    for pkg in "${REQUIRED_PKGS[@]}"; do
        if ! dpkg -s "$pkg" &> /dev/null; then
            MISSING_PKGS+=("$pkg")
        fi
    done
    
    if [ ${#MISSING_PKGS[@]} -gt 0 ]; then
        echo "[INFO] Missing packages detected: ${MISSING_PKGS[*]}"
        echo "[INFO] Installing missing packages..."
        sudo apt-get update -qq
        sudo apt-get install -y "${MISSING_PKGS[@]}"
        echo "[INFO] All required packages installed successfully"
    else
        echo "[INFO] All required packages are already installed"
    fi
}

# === Backup DNS configuration ===
backup_dns_config() {
    if [ ! -f "$DNS_BACKUP" ]; then
        echo "[INFO] Backing up original DNS configuration..."
        sudo mkdir -p /etc/router
        
        # Save current resolv.conf
        if [ -f /etc/resolv.conf ]; then
            sudo cp -L /etc/resolv.conf "$DNS_BACKUP" 2>/dev/null || true
        fi
        
        # Save systemd-resolved status if applicable
        if [ -f /etc/systemd/resolved.conf ]; then
            sudo cp /etc/systemd/resolved.conf /etc/router/resolved.conf.backup 2>/dev/null || true
        fi
        
        echo "[INFO] DNS configuration backed up to $DNS_BACKUP"
    fi
}

# === Restore DNS configuration ===
restore_dns_config() {
    echo "[INFO] Restoring DNS configuration to system defaults..."
    
    # Remove immutability flag
    sudo chattr -i /etc/resolv.conf 2>/dev/null || true
    
    # Method 1: Restore from backup if it exists
    if [ -f "$DNS_BACKUP" ]; then
        echo "[INFO] Restoring DNS from backup..."
        sudo cp "$DNS_BACKUP" /etc/resolv.conf
        sudo rm -f "$DNS_BACKUP"
    else
        # Method 2: Use systemd-resolved if available
        if systemctl is-active --quiet systemd-resolved 2>/dev/null; then
            echo "[INFO] Using systemd-resolved for DNS..."
            sudo rm -f /etc/resolv.conf
            sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
            sudo systemctl restart systemd-resolved
        # Method 3: Use NetworkManager if available
        elif systemctl is-active --quiet NetworkManager 2>/dev/null; then
            echo "[INFO] Using NetworkManager for DNS..."
            sudo rm -f /etc/resolv.conf
            sudo ln -sf /run/NetworkManager/resolv.conf /etc/resolv.conf 2>/dev/null || \
            sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf 2>/dev/null || \
            {
                echo "[INFO] Creating basic resolv.conf with fallback DNS..."
                echo "nameserver $FALLBACK_DNS1" | sudo tee /etc/resolv.conf > /dev/null
                echo "nameserver $FALLBACK_DNS2" | sudo tee -a /etc/resolv.conf > /dev/null
            }
            sudo systemctl restart NetworkManager 2>/dev/null || true
        # Method 4: Create basic resolv.conf with public DNS
        else
            echo "[INFO] Creating basic resolv.conf with public DNS servers..."
            {
                echo "# Generated by dynamic-router.sh --reset"
                echo "nameserver $FALLBACK_DNS1"
                echo "nameserver $FALLBACK_DNS2"
            } | sudo tee /etc/resolv.conf > /dev/null
        fi
    fi
    
    # Restore systemd-resolved config if backed up
    if [ -f /etc/router/resolved.conf.backup ]; then
        sudo cp /etc/router/resolved.conf.backup /etc/systemd/resolved.conf 2>/dev/null || true
        sudo rm -f /etc/router/resolved.conf.backup
        sudo systemctl restart systemd-resolved 2>/dev/null || true
    fi
    
    # Remove custom dnsmasq config
    sudo rm -f /etc/dnsmasq.d/lan.conf
    sudo rm -f /etc/systemd/resolved.conf.d/no-stub.conf 2>/dev/null || true
    
    echo "[INFO] DNS configuration restored"
    echo "[INFO] Current DNS servers:"
    cat /etc/resolv.conf | grep "^nameserver" || echo "[WARNING] No nameservers found in resolv.conf"
}

# === Reset mode ===
if [ "$1" == "--reset" ]; then
    echo "[INFO] ============================================"
    echo "[INFO] RESETTING ROUTER CONFIGURATION"
    echo "[INFO] ============================================"
    
    echo "[INFO] Stopping dynamic-router service if running..."
    sudo systemctl stop dynamic-router.service 2>/dev/null || true
    sudo systemctl disable dynamic-router.service 2>/dev/null || true
    
    echo "[INFO] Flushing iptables rules..."
    sudo iptables -F
    sudo iptables -t nat -F
    sudo iptables -t mangle -F
    sudo iptables -X
    sudo iptables -P INPUT ACCEPT
    sudo iptables -P FORWARD ACCEPT
    sudo iptables -P OUTPUT ACCEPT
    sudo rm -f /etc/iptables/rules.v4
    
    echo "[INFO] Stopping dnsmasq..."
    sudo systemctl stop dnsmasq 2>/dev/null || true
    
    # Restore DNS BEFORE restarting services
    restore_dns_config
    
    echo "[INFO] Restarting network services..."
    sudo systemctl restart dnsmasq 2>/dev/null || true
    sudo systemctl restart systemd-resolved 2>/dev/null || true
    sudo systemctl restart NetworkManager 2>/dev/null || true
    
    echo "[INFO] Removing custom netplan LAN configuration..."
    sudo rm -f /etc/netplan/99-router-lan.yaml
    sudo netplan apply 2>/dev/null || true
    
    echo "[INFO] Disabling IP forwarding..."
    sudo sysctl -w net.ipv4.ip_forward=0 2>/dev/null || true
    sudo rm -f /etc/sysctl.d/99-router.conf
    
    echo "[INFO] Cleaning up router directory..."
    sudo rm -rf /etc/router 2>/dev/null || true
    
    echo "[INFO] ============================================"
    echo "[INFO] RESET COMPLETE"
    echo "[INFO] ============================================"
    echo "[INFO] System DNS has been restored to defaults"
    echo "[INFO] Testing DNS resolution..."
    if nslookup google.com > /dev/null 2>&1 || host google.com > /dev/null 2>&1; then
        echo "[INFO] ✓ DNS is working correctly"
    else
        echo "[WARNING] DNS resolution test failed. You may need to manually configure /etc/resolv.conf"
    fi
    echo "[INFO] You can now run: $0 --install-service <LAN_IFACE> <LAN_IP/CIDR>"
    exit 0
fi

# === Parse arguments ===
if [ $# -lt 3 ]; then
    echo "Usage:"
    echo "  $0 --install-service <LAN_IFACE> <LAN_IP/CIDR> [OPTIONS]"
    echo "  $0 --run <LAN_IFACE> <LAN_IP/CIDR> [OPTIONS]"
    echo "  $0 --reset"
    echo ""
    echo "Options:"
    echo "  --vpn                 Enable VPN routing (monitors and routes VPN interfaces)"
    echo "  --subnets <file>      Path to file containing VPN subnets (one per line)"
    echo "                        Default: /etc/router/vpn-subnets.txt"
    echo ""
    echo "Examples:"
    echo "  $0 --run ens33 10.0.0.1/24"
    echo "  $0 --run ens33 10.0.0.1/24 --vpn --subnets /etc/openvpn/subnets.txt"
    echo "  $0 --install-service eth1 10.0.0.1/24"
    echo "  $0 --install-service eth1 10.0.0.1/24 --vpn"
    echo "  $0 --install-service eth1 10.0.0.1/24 --vpn --subnets /path/to/custom/vpn-subnets.txt"
    echo "  $0 --reset"
    exit 1
fi

MODE="$1"
LAN_IFACE="$2"
LAN_IP_CIDR="$3"
LAN_IP="${LAN_IP_CIDR%/*}"

# Parse optional arguments
shift 3
while [ $# -gt 0 ]; do
    case "$1" in
        --vpn)
            ENABLE_VPN_ROUTING=true
            shift
            ;;
        --subnets)
            VPN_SUBNETS_FILE="$2"
            shift 2
            ;;
        *)
            echo "[ERROR] Unknown option: $1"
            exit 1
            ;;
    esac
done

# === Install requirements first ===
check_and_install_requirements

# === Install service mode ===
if [ "$MODE" == "--install-service" ]; then
    echo "[INFO] Installing dynamic-router service..."
    
    # Backup DNS before making changes
    backup_dns_config
    
    SCRIPT_PATH="$(readlink -f "$0")"
    sudo cp "$SCRIPT_PATH" /usr/local/bin/dynamic-router.sh
    sudo chmod +x /usr/local/bin/dynamic-router.sh
    
    sudo mkdir -p /etc/router
    
    if [ ! -f "$VPN_SUBNETS_FILE" ]; then
        sudo tee "$VPN_SUBNETS_FILE" > /dev/null <<EOF
# VPN Subnets Configuration
# Add one subnet per line (CIDR notation)
# Example:
# 10.8.0.0/24
# 192.168.100.0/24
EOF
        echo "[INFO] Created empty VPN subnets file at $VPN_SUBNETS_FILE"
    fi
    
    EXEC_START_CMD="/usr/local/bin/dynamic-router.sh --run $LAN_IFACE $LAN_IP_CIDR"
    if [ "$ENABLE_VPN_ROUTING" = true ]; then
        EXEC_START_CMD="$EXEC_START_CMD --vpn"
        if [ "$VPN_SUBNETS_FILE" != "/etc/router/vpn-subnets.txt" ]; then
            EXEC_START_CMD="$EXEC_START_CMD --subnets $VPN_SUBNETS_FILE"
        fi
    fi
    
    sudo tee /etc/systemd/system/dynamic-router.service > /dev/null <<EOF
[Unit]
Description=Dynamic VM Router with VPN Support
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$EXEC_START_CMD
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
    
    sudo systemctl daemon-reload
    sudo systemctl enable dynamic-router.service
    sudo systemctl start dynamic-router.service
    
    echo "[INFO] Service installed and started."
    if [ "$ENABLE_VPN_ROUTING" = true ]; then
        echo "[INFO] VPN routing: ENABLED"
        echo "[INFO] VPN subnets file: $VPN_SUBNETS_FILE"
        echo "[INFO] Edit VPN subnets with: sudo nano $VPN_SUBNETS_FILE"
        echo "[INFO] Reload config with: sudo systemctl restart dynamic-router.service"
    else
        echo "[INFO] VPN routing: DISABLED"
        echo "[INFO] To enable VPN routing, reinstall with --vpn flag"
    fi
    echo "[INFO] Check status with: sudo systemctl status dynamic-router.service"
    echo "[INFO] View logs with: sudo journalctl -u dynamic-router.service -f"
    echo "[INFO] To reset everything: sudo /usr/local/bin/dynamic-router.sh --reset"
    exit 0
fi

# === Run mode ===
if [ "$MODE" != "--run" ]; then
    echo "[ERROR] Invalid mode: $MODE"
    exit 1
fi

echo "[INFO] Starting dynamic router setup..."
echo "[INFO] LAN Interface: $LAN_IFACE"
echo "[INFO] LAN IP: $LAN_IP_CIDR"
echo "[INFO] LAN Gateway (DNS): $LAN_IP"
if [ "$ENABLE_VPN_ROUTING" = true ]; then
    echo "[INFO] VPN Routing: ENABLED"
    echo "[INFO] VPN Subnets File: $VPN_SUBNETS_FILE"
else
    echo "[INFO] VPN Routing: DISABLED (use --vpn to enable)"
fi

# Backup DNS on first run
backup_dns_config

# === Wait for LAN interface ===
echo "[INFO] Waiting for LAN interface $LAN_IFACE..."
timeout=30
while [ $timeout -gt 0 ]; do
    if ip link show "$LAN_IFACE" &> /dev/null; then
        echo "[INFO] LAN interface $LAN_IFACE is available"
        break
    fi
    sleep 1
    ((timeout--))
done
if [ $timeout -eq 0 ]; then
    echo "[ERROR] LAN interface $LAN_IFACE not found after 30 seconds"
    exit 1
fi

# === Configure LAN interface with static IP ===
echo "[INFO] Configuring static IP on $LAN_IFACE..."
sudo ip addr flush dev "$LAN_IFACE"
sudo ip addr add "$LAN_IP_CIDR" dev "$LAN_IFACE"
sudo ip link set "$LAN_IFACE" up

sudo tee /etc/netplan/99-router-lan.yaml > /dev/null <<EOF
network:
  version: 2
  renderer: networkd
  ethernets:
    $LAN_IFACE:
      addresses:
        - $LAN_IP_CIDR
      dhcp4: no
      dhcp6: no
      optional: false
EOF
sudo netplan apply

# === Detect WAN dynamically ===
echo "[INFO] Detecting WAN interface..."
timeout=30
while [ $timeout -gt 0 ]; do
    WAN_IFACE=$(ip route | awk '/^default/ {print $5; exit}')
    if [ -n "$WAN_IFACE" ] && [ "$WAN_IFACE" != "$LAN_IFACE" ]; then
        echo "[INFO] Detected WAN interface: $WAN_IFACE"
        break
    fi
    sleep 1
    ((timeout--))
done
if [ -z "$WAN_IFACE" ]; then
    echo "[ERROR] No WAN interface with default route found after 30 seconds"
    exit 1
fi

# === Enable IP forwarding ===
echo "[INFO] Enabling IP forwarding..."
sudo sysctl -w net.ipv4.ip_forward=1
echo "net.ipv4.ip_forward=1" | sudo tee /etc/sysctl.d/99-router.conf > /dev/null

# === Detect VPN interfaces ===
detect_vpn_interfaces() {
    ip link show | grep -E '^[0-9]+: (tun|tap|ppp|wg|ipsec)[0-9]*:' | awk -F': ' '{print $2}' | awk '{print $1}'
}

# === Read VPN subnets ===
read_vpn_subnets() {
    local subnets_file="$VPN_SUBNETS_FILE"
    local line
    local subnets=()
    if [ -f "$subnets_file" ]; then
        while IFS= read -r line; do
            # Remove comments and whitespace
            line=$(echo "$line" | sed 's/#.*//' | xargs)
            if [ -n "$line" ]; then
                if [[ "$line" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}/[0-9]{1,2}$ ]]; then
                    subnets+=("$line")
                else
                    echo "[WARNING] Invalid CIDR, skipping: $line"
                fi
            fi
        done < "$subnets_file"
    fi
    # Output one subnet per line
    for subnet in "${subnets[@]}"; do
        echo "$subnet"
    done
}

# === Configure VPN routing ===
configure_vpn_routing() {
    echo "[DEBUG] Starting VPN routing configuration..."
    local vpn_ifaces=($(detect_vpn_interfaces))
    local vpn_subnets=($(read_vpn_subnets))
    
    if [ ${#vpn_ifaces[@]} -eq 0 ]; then
        echo "[INFO] No VPN interfaces detected"
        return
    fi
    
    echo "[INFO] Detected VPN interfaces: ${vpn_ifaces[*]}"
    
    if [ ${#vpn_subnets[@]} -eq 0 ]; then
        echo "[WARNING] No VPN subnets configured in $VPN_SUBNETS_FILE"
        echo "[INFO] VPN routing will use automatic route detection only"
    else
        echo "[INFO] Configured VPN subnets: ${vpn_subnets[*]}"
    fi
    
    for vpn_iface in "${vpn_ifaces[@]}"; do
        echo "[INFO] Configuring routes for VPN interface: $vpn_iface"
        sudo iptables -A FORWARD -i "$LAN_IFACE" -o "$vpn_iface" -j ACCEPT 2>/dev/null || true
        sudo iptables -A FORWARD -i "$vpn_iface" -o "$LAN_IFACE" -m state --state ESTABLISHED,RELATED -j ACCEPT 2>/dev/null || true
        sudo iptables -A INPUT -i "$vpn_iface" -j ACCEPT 2>/dev/null || true
        sudo iptables -A OUTPUT -o "$vpn_iface" -j ACCEPT 2>/dev/null || true
        sudo iptables -t nat -A POSTROUTING -o "$vpn_iface" -j MASQUERADE 2>/dev/null || true
        
        for subnet in "${vpn_subnets[@]}"; do
            if ! ip route show "$subnet" | grep -q "$vpn_iface"; then
                echo "[INFO] Adding route: $subnet via $vpn_iface"
                sudo ip route add "$subnet" dev "$vpn_iface" 2>/dev/null || echo "[WARNING] Route may already exist"
            fi
            sudo iptables -A FORWARD -s "$subnet" -i "$vpn_iface" -o "$LAN_IFACE" -j ACCEPT 2>/dev/null || true
            sudo iptables -A FORWARD -d "$subnet" -i "$LAN_IFACE" -o "$vpn_iface" -j ACCEPT 2>/dev/null || true
        done
    done
    
    sudo iptables-save | sudo tee /etc/iptables/rules.v4 > /dev/null
    echo "[INFO] VPN routing configured"
}

# === Clean up old VPN rules ===
cleanup_vpn_rules() {
    local old_vpn_ifaces="$1"
    if [ -z "$old_vpn_ifaces" ]; then
        return
    fi
    echo "[INFO] Cleaning up old VPN routes..."
    for vpn_iface in $old_vpn_ifaces; do
        if ! ip link show "$vpn_iface" &> /dev/null; then
            echo "[INFO] Removing rules for defunct VPN interface: $vpn_iface"
            sudo iptables -D FORWARD -i "$LAN_IFACE" -o "$vpn_iface" -j ACCEPT 2>/dev/null || true
            sudo iptables -D FORWARD -i "$vpn_iface" -o "$LAN_IFACE" -m state --state ESTABLISHED,RELATED -j ACCEPT 2>/dev/null || true
            sudo iptables -D INPUT -i "$vpn_iface" -j ACCEPT 2>/dev/null || true
            sudo iptables -D OUTPUT -o "$vpn_iface" -j ACCEPT 2>/dev/null || true
            sudo iptables -t nat -D POSTROUTING -o "$vpn_iface" -j MASQUERADE 2>/dev/null || true
        fi
    done
}

# === Configure iptables ===
echo "[INFO] Configuring iptables..."
sudo iptables -F
sudo iptables -t nat -F
sudo iptables -t mangle -F
sudo iptables -X
sudo iptables -P INPUT DROP
sudo iptables -P FORWARD DROP
sudo iptables -P OUTPUT ACCEPT

# Allow loopback
sudo iptables -A INPUT -i lo -j ACCEPT
sudo iptables -A OUTPUT -o lo -j ACCEPT

# Allow all traffic on LAN interface
sudo iptables -A INPUT -i $LAN_IFACE -j ACCEPT
sudo iptables -A OUTPUT -o $LAN_IFACE -j ACCEPT

# Allow established/related connections on WAN
sudo iptables -A INPUT -i $WAN_IFACE -m state --state ESTABLISHED,RELATED -j ACCEPT
sudo iptables -A OUTPUT -o $WAN_IFACE -j ACCEPT

# Allow ICMP (ping)
sudo iptables -A INPUT -p icmp -j ACCEPT
sudo iptables -A OUTPUT -p icmp -j ACCEPT

# Allow DNS queries from router itself to upstream
sudo iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
sudo iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT
sudo iptables -A INPUT -p udp --sport 53 -m state --state ESTABLISHED,RELATED -j ACCEPT
sudo iptables -A INPUT -p tcp --sport 53 -m state --state ESTABLISHED,RELATED -j ACCEPT

# Forward LAN to WAN
sudo iptables -A FORWARD -i $LAN_IFACE -o $WAN_IFACE -j ACCEPT
sudo iptables -A FORWARD -i $WAN_IFACE -o $LAN_IFACE -m state --state ESTABLISHED,RELATED -j ACCEPT

# NAT for WAN
sudo iptables -t nat -A POSTROUTING -o $WAN_IFACE -j MASQUERADE

if [ "$ENABLE_VPN_ROUTING" = true ]; then
    configure_vpn_routing
fi

sudo mkdir -p /etc/iptables
sudo iptables-save | sudo tee /etc/iptables/rules.v4 > /dev/null
echo "[INFO] Iptables configured and saved"

# === Get upstream DNS servers ===
get_upstream_dns() {
    local iface="$1"
    local dns_servers=""
    
    # Try nmcli first
    if command -v nmcli &> /dev/null; then
        dns_servers=$(nmcli dev show "$iface" 2>/dev/null | awk '/IP4.DNS/ {print $2}' | tr '\n' ' ')
    fi
    
    # Try resolvectl if nmcli didn't work
    if [ -z "$dns_servers" ] && command -v resolvectl &> /dev/null; then
        dns_servers=$(resolvectl dns "$iface" 2>/dev/null | awk '{for(i=2;i<=NF;i++) printf "%s ", $i}')
    fi
    
    # Try reading from /etc/resolv.conf as last resort
    if [ -z "$dns_servers" ] && [ -f /etc/resolv.conf ]; then
        dns_servers=$(grep "^nameserver" /etc/resolv.conf | awk '{print $2}' | tr '\n' ' ')
    fi
    
    echo "$dns_servers"
}

# === Configure router's own DNS resolution ===
configure_router_dns() {
    echo "[INFO] Configuring router's own DNS resolution..."
    
    # Get WAN DNS servers
    WAN_DNS_SERVERS=$(get_upstream_dns "$CURRENT_WAN")
    
    # Collect DNS servers in array
    declare -a DNS_ARRAY
    if [ -n "$WAN_DNS_SERVERS" ]; then
        for dns in $WAN_DNS_SERVERS; do
            # Validate IP format
            if [[ "$dns" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]]; then
                DNS_ARRAY+=("$dns")
            fi
        done
    fi
    
    # Add fallback DNS if no WAN DNS found or as backup
    if [ ${#DNS_ARRAY[@]} -eq 0 ]; then
        DNS_ARRAY+=("$FALLBACK_DNS1")
        DNS_ARRAY+=("$FALLBACK_DNS2")
        echo "[WARNING] No WAN DNS servers found, using fallback DNS"
    else
        # Add fallback as backup
        DNS_ARRAY+=("$FALLBACK_DNS1")
        DNS_ARRAY+=("$FALLBACK_DNS2")
    fi
    
    # Configure the router's own /etc/resolv.conf
    # Make sure it's not immutable
    sudo chattr -i /etc/resolv.conf 2>/dev/null || true
    
    # If resolv.conf is a symlink, remove it first
    if [ -L /etc/resolv.conf ]; then
        sudo rm -f /etc/resolv.conf
    fi
    
    # Ensure the file exists and is writable
    sudo touch /etc/resolv.conf 2>/dev/null || true
    
    # Write directly to /etc/resolv.conf for the router itself
    {
        echo "# Router's own DNS resolution (managed by dynamic-router.sh)"
        echo "# LAN clients will use dnsmasq at $LAN_IP"
        echo ""
        for dns in "${DNS_ARRAY[@]}"; do
            echo "nameserver $dns"
        done
    } | sudo tee /etc/resolv.conf > /dev/null
    
    echo "[INFO] Router DNS configured: ${DNS_ARRAY[*]}"
    
    # Test DNS resolution
    echo "[INFO] Testing router's DNS resolution..."
    if timeout 5 nslookup google.com ${DNS_ARRAY[0]} > /dev/null 2>&1; then
        echo "[INFO] ✓ Router DNS is working"
    else
        echo "[WARNING] ⚠ Router DNS test failed, but continuing..."
    fi
}

# === Update dnsmasq based on WAN DNS ===
update_dnsmasq_upstream() {
    echo "[INFO] Configuring dnsmasq for LAN clients..."
    
    WAN_DNS_SERVERS=$(get_upstream_dns "$CURRENT_WAN")
    
    declare -a SERVER_LINES
    if [ -n "$WAN_DNS_SERVERS" ]; then
        for dns in $WAN_DNS_SERVERS; do
            if [[ "$dns" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]]; then
                SERVER_LINES+=("server=$dns")
            fi
        done
    fi
    
    # Always add fallback DNS
    SERVER_LINES+=("server=$FALLBACK_DNS1")
    SERVER_LINES+=("server=$FALLBACK_DNS2")
    
    if [ ${#SERVER_LINES[@]} -eq 2 ]; then
        echo "[WARNING] No WAN DNS servers found, using fallback only"
    fi
    
    # Configure dnsmasq
    {
        echo "# dnsmasq configuration for LAN"
        echo "interface=$LAN_IFACE"
        echo "listen-address=$LAN_IP"
        echo "bind-interfaces"
        echo ""
        echo "# Upstream DNS servers"
        for line in "${SERVER_LINES[@]}"; do
            echo "$line"
        done
        echo ""
        echo "# Don't read /etc/resolv.conf"
        echo "no-resolv"
        echo ""
        echo "# Only answer DNS queries from LAN"
        echo "local-service"
        echo ""
        echo "# Don't forward plain names"
        echo "domain-needed"
        echo ""
        echo "# Don't forward private IP reverse lookups"
        echo "bogus-priv"
        echo ""
        echo "# DNS cache size"
        echo "cache-size=1000"
        echo ""
        echo "# DHCP settings"
        echo "dhcp-range=${LAN_IP%.*}.100,${LAN_IP%.*}.250,12h"
        echo "dhcp-option=option:router,$LAN_IP"
        echo "dhcp-option=option:dns-server,$LAN_IP"
        echo "dhcp-authoritative"
        echo ""
        echo "# Logging"
        echo "log-queries"
        echo "log-dhcp"
    } | sudo tee /etc/dnsmasq.d/lan.conf > /dev/null
    
    # Restart dnsmasq
    echo "[INFO] Restarting dnsmasq..."
    sudo systemctl restart dnsmasq
    
    # Check if dnsmasq started successfully
    sleep 2
    if sudo systemctl is-active --quiet dnsmasq; then
        echo "[INFO] ✓ dnsmasq is running"
    else
        echo "[ERROR] ✗ dnsmasq failed to start!"
        sudo journalctl -u dnsmasq -n 20 --no-pager
        return 1
    fi
    
    echo "[INFO] dnsmasq configured:"
    echo "[INFO]   - LAN clients will use $LAN_IP as DNS server (gateway)"
    echo "[INFO]   - LAN clients will use $LAN_IP as default gateway"
    echo "[INFO]   - Upstream DNS: ${WAN_DNS_SERVERS:-$FALLBACK_DNS1 $FALLBACK_DNS2}"
    
    # Test dnsmasq DNS resolution
    echo "[INFO] Testing dnsmasq DNS forwarding..."
    if timeout 5 dig @$LAN_IP google.com +short > /dev/null 2>&1; then
        echo "[INFO] ✓ dnsmasq DNS forwarding is working"
    else
        echo "[WARNING] ⚠ dnsmasq DNS test failed, but continuing..."
    fi
    
    # Also configure the router's own DNS
    configure_router_dns
}

# === WAN and VPN monitoring ===
CURRENT_WAN=$WAN_IFACE
CURRENT_VPN_IFACES=""

echo "[INFO] Performing initial DNS and routing setup..."
update_dnsmasq_upstream

ensure_lan_ip() {
    CURRENT_LAN_IP=$(ip addr show "$LAN_IFACE" 2>/dev/null | grep "inet " | awk '{print $2}')
    if [ "$CURRENT_LAN_IP" != "$LAN_IP_CIDR" ]; then
        echo "[WARNING] LAN IP missing or incorrect. Reapplying..."
        sudo ip addr flush dev "$LAN_IFACE" 2>/dev/null || true
        sudo ip addr add "$LAN_IP_CIDR" dev "$LAN_IFACE"
        sudo ip link set "$LAN_IFACE" up
        echo "[INFO] LAN IP restored: $LAN_IP_CIDR"
    fi
}

# === Diagnostic function ===
print_diagnostics() {
    echo ""
    echo "[DIAGNOSTICS] ================================"
    echo "[DIAGNOSTICS] Router Status:"
    echo "[DIAGNOSTICS] ================================"
    echo "[DIAGNOSTICS] WAN Interface: $CURRENT_WAN"
    echo "[DIAGNOSTICS] LAN Interface: $LAN_IFACE ($LAN_IP_CIDR)"
    echo "[DIAGNOSTICS] IP Forwarding: $(cat /proc/sys/net/ipv4/ip_forward)"
    echo ""
    echo "[DIAGNOSTICS] Router DNS (/etc/resolv.conf):"
    cat /etc/resolv.conf | grep "nameserver" | head -3
    echo ""
    echo "[DIAGNOSTICS] dnsmasq status:"
    sudo systemctl is-active dnsmasq && echo "  ✓ Running" || echo "  ✗ Not running"
    echo ""
    echo "[DIAGNOSTICS] Active NAT rules:"
    sudo iptables -t nat -L POSTROUTING -n -v | grep MASQUERADE | head -3
    echo ""
    echo "[DIAGNOSTICS] Routing table:"
    ip route show | head -5
    echo "[DIAGNOSTICS] ================================"
    echo ""
}

# Print initial diagnostics
print_diagnostics

echo "[INFO] ============================================"
echo "[INFO] Router setup complete!"
echo "[INFO] ============================================"
echo "[INFO] LAN clients should now:"
echo "[INFO]   1. Get IP addresses via DHCP (${LAN_IP%.*}.100-250)"
echo "[INFO]   2. Use $LAN_IP as gateway and DNS server"
echo "[INFO]   3. Have internet access through $CURRENT_WAN"
echo "[INFO] ============================================"
echo "[INFO] To test from a LAN client:"
echo "[INFO]   ping $LAN_IP          # Test gateway"
echo "[INFO]   ping 8.8.8.8          # Test routing"
echo "[INFO]   ping google.com       # Test DNS"
echo "[INFO] ============================================"
echo "[INFO] Starting WAN and VPN interface monitor..."

while true; do
    sleep 10
    ensure_lan_ip

    NEW_WAN=$(ip route | awk '/^default/ {print $5; exit}')
    if [ "$NEW_WAN" != "$CURRENT_WAN" ] && [ -n "$NEW_WAN" ]; then
        echo "[INFO] WAN interface changed: $CURRENT_WAN -> $NEW_WAN"
        CURRENT_WAN="$NEW_WAN"
        update_dnsmasq_upstream  # This also updates router's own DNS
        
        # Update NAT rule for new WAN interface
        sudo iptables -t nat -D POSTROUTING -o "$CURRENT_WAN" -j MASQUERADE 2>/dev/null || true
        sudo iptables -t nat -A POSTROUTING -o "$CURRENT_WAN" -j MASQUERADE
        sudo iptables -A INPUT -i "$NEW_WAN" -m state --state ESTABLISHED,RELATED -j ACCEPT 2>/dev/null || true
        sudo iptables -A OUTPUT -o "$NEW_WAN" -j ACCEPT 2>/dev/null || true
        sudo iptables -A FORWARD -i "$LAN_IFACE" -o "$NEW_WAN" -j ACCEPT 2>/dev/null || true
        sudo iptables -A FORWARD -i "$NEW_WAN" -o "$LAN_IFACE" -m state --state ESTABLISHED,RELATED -j ACCEPT 2>/dev/null || true
        
        sudo iptables-save | sudo tee /etc/iptables/rules.v4 > /dev/null
        
        print_diagnostics
    fi

    if [ "$ENABLE_VPN_ROUTING" = true ]; then
        VPN_IFACES=$(detect_vpn_interfaces)
        if [ "$VPN_IFACES" != "$CURRENT_VPN_IFACES" ]; then
            echo "[INFO] VPN interfaces changed: $CURRENT_VPN_IFACES -> $VPN_IFACES"
            cleanup_vpn_rules "$CURRENT_VPN_IFACES"
            CURRENT_VPN_IFACES="$VPN_IFACES"
            configure_vpn_routing
        fi
    fi
done
